### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by Alvinhech** [ypeleg/HungaBunga#2]
I want to run your sample code, but it shows some errors. I guess it is something wrong with the setup. But you don't provide like setup.py. So how do we setup this package?

**Comment by ryan-anderson-ds** [comment]
if you're getting the same errors I got (ModuleNotFoundError), then:

It's a relative/absolute import issue. If we want to contain all of the source files to the hunga_bunga folder, an easy fix is to edit the imports in regression.py, classification.py and \_init.py___ to reference the folder they are in.

e.g. in \_init.py___ change:

from regression import HungaBungaRegressor from classification import HungaBungaClassifier

to

from hunga_bunga.regression import HungaBungaRegressor from hunga_bunga.classification import HungaBungaClassifier

and do the equivalent for the other source files where it throws import errors.

I'm sure there's a more elegant solution, but I couldn't find one quickly, and this quick fix works :)
